//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFS.DB.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFS.DB.WebApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit amount must be greater than 0.00.
        /// </summary>
        public static string creditamount_error_msg {
            get {
                return ResourceManager.GetString("creditamount_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string customer_id {
            get {
                return ResourceManager.GetString("customer_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash board.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world!.
        /// </summary>
        public static string helloworld {
            get {
                return ResourceManager.GetString("helloworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date must be greater than today..
        /// </summary>
        public static string paymentdate_error_msg {
            get {
                return ResourceManager.GetString("paymentdate_error_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string payments {
            get {
                return ResourceManager.GetString("payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Security Details?.
        /// </summary>
        public static string question_forgot_security_details {
            get {
                return ResourceManager.GetString("question_forgot_security_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string signin {
            get {
                return ResourceManager.GetString("signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access your account, please enter your Customer ID and and Security Details.
        /// </summary>
        public static string signin_notification_msg {
            get {
                return ResourceManager.GetString("signin_notification_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the following characters from your Password code..
        /// </summary>
        public static string signin_passwrod_notification_msg {
            get {
                return ResourceManager.GetString("signin_passwrod_notification_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use your mouse to click on the keypad to enter your security code..
        /// </summary>
        public static string signin_securitycode_notification_msg {
            get {
                return ResourceManager.GetString("signin_securitycode_notification_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Identification.
        /// </summary>
        public static string signin_title {
            get {
                return ResourceManager.GetString("signin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing Queues.
        /// </summary>
        public static string signing_queues {
            get {
                return ResourceManager.GetString("signing_queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Orders.
        /// </summary>
        public static string standing_orders {
            get {
                return ResourceManager.GetString("standing_orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfers.
        /// </summary>
        public static string transfers {
            get {
                return ResourceManager.GetString("transfers", resourceCulture);
            }
        }
    }
}
